# Generated by Django 5.1.4 on 2025-02-20 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0002_vente'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
