# Generated by Django 5.1.4 on 2025-02-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0006_ecouteurvente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
