# Generated by Django 5.1.4 on 2025-02-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0007_vente_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeurvente',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
