# Generated by Django 5.1.4 on 2025-02-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0008_chargeurvente_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecouteurvente',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
