# Generated by Django 5.1.4 on 2025-03-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0009_ecouteurvente_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayerProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('modpayement', models.CharField(max_length=100)),
                ('montantpayer', models.IntegerField()),
                ('telephone', models.IntegerField()),
            ],
        ),
    ]
