# Generated by Django 5.1.4 on 2025-03-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0010_payerproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payerproduit',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payerproduit',
            name='telephone',
            field=models.CharField(max_length=100),
        ),
    ]
