# Generated by Django 5.1.4 on 2025-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0011_alter_payerproduit_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payerproduit',
            name='produit',
            field=models.CharField(default='prod', max_length=100),
        ),
    ]
