# Generated by Django 5.1.4 on 2025-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0012_payerproduit_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payerproduit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits2p/'),
        ),
    ]
