# Generated by Django 5.1.4 on 2025-03-19 19:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0013_payerproduit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payerproduit',
            name='date_achat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
