# Generated by Django 5.1.4 on 2025-03-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0014_payerproduit_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payerproduit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits3/'),
        ),
    ]
