# Generated by Django 5.1.4 on 2025-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoutiqueEnligne', '0016_alter_payerproduit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeurvente',
            name='stock_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecouteurvente',
            name='stock_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payerproduit',
            name='commande_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='stock_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
