# Generated by Django 5.1.4 on 2025-02-16 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boubou',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomproduit', models.CharField(default='Boubuo', max_length=100)),
                ('tussi', models.CharField(max_length=100)),
                ('prixinit', models.IntegerField(default=0)),
                ('prixtot', models.IntegerField(default=0)),
                ('quantite', models.IntegerField()),
                ('benefice', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameclient', models.CharField(max_length=100)),
                ('numtel', models.IntegerField()),
                ('prix', models.IntegerField(null=True)),
                ('avance', models.IntegerField(default=0)),
                ('restavance', models.IntegerField(default=0)),
                ('nametussi', models.CharField(max_length=200)),
                ('dessin', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('datevenir', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('daterevenir', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entreesorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(default='', max_length=100)),
                ('typeO1', models.CharField(default='', max_length=100)),
                ('prix', models.IntegerField()),
                ('benefice', models.IntegerField(default=0)),
                ('travailleur', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Loginn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('telephonn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.IntegerField()),
                ('quiprend', models.CharField(max_length=100)),
                ('descriptionsortie', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesf', models.CharField(max_length=100)),
                ('datecommence', models.DateTimeField()),
                ('saleur', models.IntegerField(default=0)),
                ('benefice', models.IntegerField(default=0)),
                ('prendre', models.IntegerField(default=0)),
                ('rset', models.IntegerField(default=0)),
            ],
        ),
    ]
