# Generated by Django 5.1.4 on 2025-02-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boubou',
            new_name='Produit',
        ),
    ]
