# Generated by Django 5.1.4 on 2025-02-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0002_rename_boubou_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
