# Generated by Django 5.1.4 on 2025-02-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0003_produit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='nomproduit',
            field=models.CharField(default='tel', max_length=100),
        ),
    ]
