# Generated by Django 5.1.4 on 2025-02-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0004_alter_produit_nomproduit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='benefice',
        ),
    ]
