# Generated by Django 5.1.4 on 2025-02-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0008_produit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecouteur',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
