# Generated by Django 5.1.4 on 2025-02-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0009_ecouteur_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecouteur',
            name='description',
        ),
        migrations.AddField(
            model_name='chargeur',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
