# Generated by Django 5.1.4 on 2025-02-26 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0010_remove_ecouteur_description_chargeur_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecouteur',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
