# Generated by Django 5.1.4 on 2025-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0012_livreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='chargeur_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='ecouteur_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='commandes/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='commandes/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='commandes/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_selected',
            field=models.BooleanField(default=False),
        ),
    ]
