# Generated by Django 5.1.4 on 2025-03-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gesionstoke', '0016_delete_entreesorie_delete_livreur_delete_sortie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeur',
            name='vente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='client_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ecouteur',
            name='vente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='vente_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
